// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofatrytflsrcphlaqscu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mYXRyeXRmbHNyY3BobGFxc2N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTU2OTYsImV4cCI6MjA2MzU5MTY5Nn0.bc2qi_sEvvEhLz9VuwzWPFlrzRZGFuXsD3_znhrjKn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);